using System;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace MVP_API
{
    public class Note
    {
        public  Note()
        {
            Id = ObjectId.GenerateNewId().ToString();
        }

        [BsonId]
        // standard BSonId generated by MongoDb
        public string Id { get; set; }

        public string Body { get; set; } = string.Empty;

        [BsonDateTimeOptions(Kind = DateTimeKind.Local)]
        public DateTime UpdatedOn { get; set; } = DateTime.Now;

        public int UserId { get; set; } = 0;
    }
}